In [2]:
import pandas as pd   
import matplotlib.pyplot as plt
import plotly.express as px
import time
import numpy as np
import warnings


from sklearn.pipeline import Pipeline
from matplotlib import pyplot
# the permutation based importance
import seaborn as sns

from numpy import mean
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Importing Dataset using Pandas.
data = pd.read_csv("E:/online_shoppers_intention.csv")
data.shape

(12330, 18)

In [4]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [5]:
data.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [7]:
data.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [8]:
data['Month'].unique()

array(['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep',
       'Dec'], dtype=object)

In [9]:
data['VisitorType'].unique()

array(['Returning_Visitor', 'New_Visitor', 'Other'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()                                 #encode the education column
label=le.fit_transform(data['Revenue'])
label
data.drop('Revenue',axis=1)
data['Revenue']=label

label1=le.fit_transform(data['Weekend'])   #encode the marital_Status column
data.drop('Weekend',axis=1)
data['Weekend']=label1
data

label1=le.fit_transform(data['VisitorType'])   #encode the marital_Status column
data.drop('VisitorType',axis=1)
data['Visitor Type']=label1
data

label1=le.fit_transform(data['Month'])   #encode the marital_Status column
data.drop('Month',axis=1)
data['Month']=label1
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue,Visitor Type
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,Returning_Visitor,0,0,2
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,Returning_Visitor,0,0,2
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,Returning_Visitor,0,0,2
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,Returning_Visitor,0,0,2
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,Returning_Visitor,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,1,4,6,1,1,Returning_Visitor,1,0,2
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,7,3,2,1,8,Returning_Visitor,1,0,2
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,7,3,2,1,13,Returning_Visitor,1,0,2
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,7,2,2,3,11,Returning_Visitor,0,0,2
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,7,3,2,1,2,New_Visitor,1,0,0

In [11]:
data = data.drop('VisitorType',axis=1)

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()

scaling.fit(data)
data_scaled = scaling.transform(data)

In [13]:
data_scaled = pd.DataFrame(data_scaled, columns= data.columns)

In [14]:
data_scaled.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,Weekend,Revenue,Visitor Type
0,0.0,0.0,0.0,0.0,0.001418,0.000000,1.00,1.00,0.0,0.0,0.222222,0.000000,0.000000,0.000,0.000000,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.002837,0.001000,0.00,0.50,0.0,0.0,0.222222,0.142857,0.083333,0.000,0.052632,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.001418,0.000000,1.00,1.00,0.0,0.0,0.222222,0.428571,0.000000,1.000,0.105263,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.002837,0.000042,0.25,0.70,0.0,0.0,0.222222,0.285714,0.083333,0.125,0.157895,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.014184,0.009809,0.10,0.25,0.0,0.0,0.222222,0.285714,0.166667,0.000,0.157895,1.0,0.0,1.0

## Clustering Analysis

### Mini Batch K-Mean Algorithm

In [15]:
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics.cluster import fowlkes_mallows_score
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.metrics import v_measure_score
from sklearn.metrics import homogeneity_score



kmeans = MiniBatchKMeans(n_clusters=6, random_state=0, batch_size=6)
data_scaled["Cluster"] = kmeans.fit_predict(data_scaled)

In [16]:
labels_pred = data_scaled["Cluster"]
true_label = data_scaled['Revenue']

In [17]:
score = silhouette_score(data_scaled, kmeans.labels_, metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels_pred)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels_pred)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels_pred)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels_pred)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels_pred)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.4895057515059258
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.8194757330948333
--------------------------------------------------------------
Fowkles Marrow Score is: 0.5276220161670496
--------------------------------------------------------------
ARI is: 0.005459272651202828
--------------------------------------------------------------
Mutual Info Value is: 0.03481187891813586
--------------------------------------------------------------
Mutual Info is: 0.03481187891813586
--------------------------------------------------------------
Homogeneity Score is: 0.07102162932157319

### Algomarative Clustering

In [19]:
from sklearn.cluster import AgglomerativeClustering
clustering_model = AgglomerativeClustering(n_clusters=6, linkage="ward")
data_scaled["Cluster"] = clustering_model.fit_predict(data_scaled)

In [20]:
labels_pred = data_scaled["Cluster"]
true_label = data_scaled['Revenue']

In [22]:
score = silhouette_score(data_scaled, labels_pred , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels_pred)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels_pred)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels_pred)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels_pred)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels_pred)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.5299104198474474
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.7998258599175222
--------------------------------------------------------------
Fowkles Marrow Score is: 0.6037503161074643
--------------------------------------------------------------
ARI is: 0.21600726531076772
--------------------------------------------------------------
Mutual Info Value is: 0.29492797403252946
--------------------------------------------------------------
Mutual Info is: 0.29492797403252946
--------------------------------------------------------------
Homogeneity Score is: 0.6639458225276542

### DBSCAN

In [23]:
from sklearn.cluster import DBSCAN
epsilon = 1.0
min_samples = 13

labels = DBSCAN(eps=epsilon, min_samples=min_samples).fit_predict(data_scaled)

In [24]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.4991247159103149
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.7998258599175222
--------------------------------------------------------------
Fowkles Marrow Score is: 0.6145320364939646
--------------------------------------------------------------
ARI is: 0.24098549970358993
--------------------------------------------------------------
Mutual Info Value is: 0.4017572557049706
--------------------------------------------------------------
Mutual Info is: 0.4017572557049706
--------------------------------------------------------------
Homogeneity Score is: 0.9953973784934765

### OPTICS Model

In [25]:
from sklearn.cluster import OPTICS

labels = OPTICS(min_samples=3).fit_predict(data_scaled)

In [26]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: -0.43270758881480564
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.7998258599175222
--------------------------------------------------------------
Fowkles Marrow Score is: 0.5417734682073475
--------------------------------------------------------------
ARI is: -0.036329829938353445
--------------------------------------------------------------
Mutual Info Value is: 0.0766057900635261
--------------------------------------------------------------
Mutual Info is: 0.0766057900635261
--------------------------------------------------------------
Homogeneity Score is: 0.3070169293818273

### MEAN Shift Algorithm

In [27]:
from sklearn.cluster import MeanShift

labels = MeanShift().fit_predict(data_scaled)

In [28]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.5221279423423314
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.7998258599175222
--------------------------------------------------------------
Fowkles Marrow Score is: 0.6709238961005236
--------------------------------------------------------------
ARI is: 0.17588012964301475
--------------------------------------------------------------
Mutual Info Value is: 0.15684034455742327
--------------------------------------------------------------
Mutual Info is: 0.15684034455742327
--------------------------------------------------------------
Homogeneity Score is: 0.23493003180470962