In [25]:
import pandas as pd   
import matplotlib.pyplot as plt
import plotly.express as px
import time
import numpy as np
import warnings


from sklearn.pipeline import Pipeline
from matplotlib import pyplot
# the permutation based importance
import seaborn as sns

from numpy import mean
import warnings
warnings.filterwarnings("ignore")

In [26]:
# Importing Dataset using Pandas.
data = pd.read_csv("E:/creditcard.csv")
data.shape

(284807, 31)

In [27]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [28]:
data = data.sample(n=15000, replace=True)

In [29]:
data.shape

(15000, 31)

## Data Pre Processing

In [30]:
data.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
109839,71561.0,-0.751983,0.715473,-0.226630,-1.945369,-0.034326,-0.917455,1.008401,0.190895,0.719306,...,0.126360,0.423925,-0.046887,-0.438756,0.109446,-0.769018,0.285408,0.178086,95.20,0
181119,124831.0,-2.200528,-0.531042,-5.850541,-1.023516,-3.934897,2.423827,-0.975413,-12.454357,-1.663108,...,-5.120828,2.033085,-9.061632,1.405845,-2.586020,-0.272784,2.103529,0.046230,2000.00,0
282734,171103.0,-0.840881,-1.416576,-0.138735,0.020161,2.028243,-2.212531,-0.227380,-0.082323,0.301592,...,-0.007217,-0.534653,0.562210,-0.133662,-0.625288,0.142359,-0.101463,0.022272,38.41,0
240652,150694.0,1.813710,-1.314657,-3.155547,-1.219877,1.084749,0.676725,0.291527,-0.015515,-1.177104,...,0.665251,1.566516,-0.365716,-0.856585,0.530669,0.364058,-0.097395,-0.082288,204.00,0
21860,31899.0,1.257495,-0.056524,0.314711,-0.111176,-0.497538,-0.702201,-0.150883,-0.055637,0.358779,...,-0.091520,-0.244217,0.085499,0.126769,0.143506,0.992389,-0.071936,-0.001474,1.46,0

In [31]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15000 entries, 109839 to 231316
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    15000 non-null  float64
 1   V1      15000 non-null  float64
 2   V2      15000 non-null  float64
 3   V3      15000 non-null  float64
 4   V4      15000 non-null  float64
 5   V5      15000 non-null  float64
 6   V6      15000 non-null  float64
 7   V7      15000 non-null  float64
 8   V8      15000 non-null  float64
 9   V9      15000 non-null  float64
 10  V10     15000 non-null  float64
 11  V11     15000 non-null  float64
 12  V12     15000 non-null  float64
 13  V13     15000 non-null  float64
 14  V14     15000 non-null  float64
 15  V15     15000 non-null  float64
 16  V16     15000 non-null  float64
 17  V17     15000 non-null  float64
 18  V18     15000 non-null  float64
 19  V19     15000 non-null  float64
 20  V20     15000 non-null  float64
 21  V21     15000 non-null  float64
 22  V22     15000 non-null  float64
 23  V23     15000 non-null  float64
 24  V24     15000 non-null  float64
 25  V25     15000 non-null  float64
 26  V26     15000 non-null  float64
 27  V27     15000 non-null  float64
 28  V28     15000 non-null  float64
 29  Amount  15000 non-null  float64
 30  Class   15000 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 3.7 MB

In [33]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [34]:
data.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [35]:
data.drop('Time',axis=1,inplace=True)

In [36]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
V1,15000.0,-0.013603,1.983910,-31.322895,-0.941504,0.000381,1.315792,2.418267
V2,15000.0,-0.009118,1.707788,-35.097685,-0.594203,0.065580,0.802166,14.044567
V3,15000.0,0.010841,1.504959,-26.278701,-0.879909,0.183696,1.039233,4.017561
V4,15000.0,-0.002046,1.410698,-5.047408,-0.841706,-0.035025,0.709803,11.824990
V5,15000.0,0.016596,1.454876,-32.092129,-0.686011,-0.051725,0.623742,34.099309
V6,15000.0,0.006691,1.380341,-23.496714,-0.778330,-0.268872,0.423771,21.393069
V7,15000.0,0.001062,1.289440,-26.548144,-0.539188,0.040915,0.573656,34.303177
V8,15000.0,-0.015399,1.232795,-34.535000,-0.212762,0.021000,0.326836,16.213627
V9,15000.0,0.005909,1.099324,-8.630390,-0.631492,-0.046336,0.600941,7.938980
V10,15000.0,0.002183,1.078657,-16.255612,-0.535671,-0.089766,0.442435,12.026538
V11,15000.0,0.007491,1.013592,-3.610426,-0.752997,-0.028559,0.734613,9.567110
V12,15000.0,-0.000710,0.997060,-15.592323,-0.407672,0.140486,0.624557,4.574082
V13,15000.0,0.005911,0.996020,-3.888606,-0.639310,-0.006437,0.667346,4.465413
V14,15000.0,-0.001317,0.950069,-13.969471,-0.430522,0.050434,0.484403,7.667726
V15,15000.0,0.006958,0.915946,-3.875765,-0.569759,0.057503,0.650529,4.153006
V16,15000.0,0.005480,0.864004,-10.954286,-0.469671,0.067964,0.527587,5.562388
V17,15000.0,0.004547,0.814030,-20.583593,-0.482047,-0.067439,0.400095,5.573078
V18,15000.0,-0.005879,0.839048,-7.517262,-0.500952,-0.011524,0.498419,4.079390
V19,15000.0,0.001171,0.812202,-4.197145,-0.458597,-0.000852,0.462160,4.555359
V20,15000.0,0.004258,0.802671,-20.207940,-0.206327,-0.057558,0.139523,17.885238
V21,15000.0,-0.003393,0.783793,-16.640785,-0.227874,-0.031420,0.186070,22.614889
V22,15000.0,-0.006070,0.722677,-8.593642,-0.538656,0.002294,0.521471,5.707723
V23,15000.0,-0.000733,0.675359,-30.269720,-0.160647,-0.010421,0.148096,19.228169
V24,15000.0,-0.002539,0.612023,-2.681724,-0.359994,0.039281,0.441242,3.629724
V25,15000.0,-0.000817,0.514713,-6.429334,-0.314407,0.014985,0.352291,5.525093
V26,15000.0,0.005037,0.487104,-1.652533,-0.325315,-0.050154,0.248045,3.463246
V27,15000.0,-0.001583,0.403564,-8.839766,-0.072470,0.000373,0.088930,8.254376
V28,15000.0,0.000028,0.355964,-8.464609,-0.053970,0.011208,0.079978,15.619041
Amount,15000.0,88.778335,249.429462,0.000000,5.380000,21.040000,77.000000,8360.000000
Class,15000.0,0.001533,0.039129,0.000000,0.000000,0.000000,0.000000,1.000000

In [37]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()

scaling.fit(data)
data_scaled = scaling.transform(data)

In [38]:
data_scaled = pd.DataFrame(data_scaled, columns= data.columns)

In [39]:
data_scaled.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.906042,0.728765,0.859910,0.183853,0.484319,0.502993,0.452850,0.684273,0.564276,0.515204,...,0.427127,0.630539,0.610588,0.355381,0.546976,0.172704,0.533819,0.358861,0.011388,0.0
1,0.863111,0.703400,0.674280,0.238490,0.425391,0.577426,0.420249,0.435098,0.420492,0.516134,...,0.293460,0.743057,0.428464,0.647644,0.321497,0.269705,0.640178,0.353387,0.239234,0.0
2,0.903407,0.685380,0.862812,0.300347,0.515480,0.474143,0.432542,0.678889,0.539066,0.562019,...,0.423724,0.563512,0.622894,0.403721,0.485514,0.350854,0.511187,0.352392,0.004594,0.0
3,0.982083,0.687454,0.763235,0.226852,0.501226,0.538506,0.441070,0.680205,0.449823,0.606898,...,0.440854,0.710433,0.604147,0.289179,0.582211,0.394190,0.511425,0.348050,0.024402,0.0
4,0.965598,0.713056,0.877779,0.292563,0.477321,0.507788,0.433799,0.679415,0.542517,0.567251,...,0.421576,0.583820,0.613263,0.444984,0.549825,0.517013,0.512914,0.351406,0.000175,0.0

## Cluster Analysis

### K Mean Clustering

In [40]:
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics.cluster import fowlkes_mallows_score
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.metrics import v_measure_score
from sklearn.metrics import homogeneity_score



kmeans = MiniBatchKMeans(n_clusters=6, random_state=0, batch_size=6)
data_scaled["Cluster"] = kmeans.fit_predict(data_scaled)

In [41]:
labels_pred = data_scaled["Cluster"]
true_label = data_scaled['Class']

In [42]:
score = silhouette_score(data_scaled, kmeans.labels_, metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels_pred)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels_pred)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels_pred)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels_pred)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels_pred)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.6466034024129023
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.5536675787224434
--------------------------------------------------------------
Fowkles Marrow Score is: 0.5161171009399249
--------------------------------------------------------------
ARI is: 0.001139670693286459
--------------------------------------------------------------
Mutual Info Value is: 0.0014642638328815208
--------------------------------------------------------------
Mutual Info is: 0.0014642638328815208
--------------------------------------------------------------
Homogeneity Score is: 0.09550264139651078

### Agglomarative Clustering

In [43]:
from sklearn.cluster import AgglomerativeClustering
clustering_model = AgglomerativeClustering(n_clusters=3, linkage="ward")
data_scaled["Cluster"] = clustering_model.fit_predict(data_scaled)

In [44]:
score = silhouette_score(data_scaled, kmeans.labels_, metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels_pred)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels_pred)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels_pred)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels_pred)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels_pred)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.20347999883077403
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.5658235573890426
--------------------------------------------------------------
Fowkles Marrow Score is: 0.5161171009399249
--------------------------------------------------------------
ARI is: 0.001139670693286459
--------------------------------------------------------------
Mutual Info Value is: 0.0014642638328815208
--------------------------------------------------------------
Mutual Info is: 0.0014642638328815208
--------------------------------------------------------------
Homogeneity Score is: 0.09550264139651078

### OPTICS Model

In [45]:
from sklearn.cluster import OPTICS

labels = OPTICS(min_samples=3).fit_predict(data_scaled)

In [ ]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: -0.36854445782804895
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.6149503073838394
--------------------------------------------------------------
Fowkles Marrow Score is: 0.631938717943695
--------------------------------------------------------------
ARI is: 0.0008656554346935395
--------------------------------------------------------------
Mutual Info Value is: 0.0037651215078167506
--------------------------------------------------------------
Mutual Info is: 0.0037651215078167506
--------------------------------------------------------------
Homogeneity Score is: 0.46738157521805435

### DBSCAN Model

In [ ]:
from sklearn.cluster import DBSCAN
epsilon = 1.0
min_samples = 13

labels = DBSCAN(eps=epsilon, min_samples=min_samples).fit_predict(data_scaled)

In [ ]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )

Silhouetter Score is: 0.6471306673197352
--------------------------------------------------------------
DB Index (Davies-Bouldin index) is : 0.6149503073838394
--------------------------------------------------------------
Fowkles Marrow Score is: 0.6577233605733744
--------------------------------------------------------------
ARI is: 0.005449893996270744
--------------------------------------------------------------
Mutual Info Value is: 0.026852905935722475
--------------------------------------------------------------
Mutual Info is: 0.026852905935722475
--------------------------------------------------------------
Homogeneity Score is: 0.9829716312332663

### Mean Shift

In [ ]:
from sklearn.cluster import MeanShift

labels = MeanShift().fit_predict(data_scaled)

In [ ]:
score = silhouette_score(data_scaled, labels , metric='euclidean')
print("Silhouetter Score is:", score)
print("--------------------------------------------------------------")

db_index = davies_bouldin_score(data_scaled, data_scaled["Cluster"] )
print("DB Index (Davies-Bouldin index) is :", db_index)
print("--------------------------------------------------------------")

fowlkes = fowlkes_mallows_score(true_label, labels)
print("Fowkles Marrow Score is:",fowlkes)
print("--------------------------------------------------------------")

ARI = adjusted_rand_score(true_label, labels)
print("ARI is:", ARI)

print("--------------------------------------------------------------")
mutual_info = normalized_mutual_info_score (true_label, labels)
print("Mutual Info Value is:", mutual_info)

print("--------------------------------------------------------------")
v_scores = v_measure_score(true_label, labels)
print("Mutual Info is:", mutual_info)

print("--------------------------------------------------------------")
homo_score = homogeneity_score(true_label, labels)
print("Homogeneity Score is:",homo_score )